pipeline {
    agent any

    stages {

        stage('Настройка виртуального окружения') {
            steps {
                script {
                    sh '''
                    venv_dir=lab2/.venv
                    python3 -m venv $venv_dir               
                    source $venv_dir/bin/activate
                    pip3 install -r lab2/requirements.txt
                    '''
                }
            }
        }

        stage('Переход в папку скриптов') {
            steps {
                script {
                    sh 'cd lab2/src'
                }
            }
        }

        stage('Генерация данных') {
            steps {
                script {
                    sh '''cd lab2/src
                    lab2/.venv/bin/python3 data_creation.py'''
                }
            }
        }

        stage('Предобработка данных') {
            steps {
                script {
                    sh 'lab2/.venv/bin/python3 model_preparation.py'
                }
            }
        }

        stage('Обучение модели') {
            steps {
                script {
                    sh 'lab2/.venv/bin/python3 model_preprocessing.py'
                }
            }
        }

        stage('Проверка обученной модели на тестовых данных.') {
            steps {
                script {
                    sh 'lab2/.venv/bin/python3 model_testing.py'
                }
            }
        }

        stage('Завершение') {
            steps {
                script {
                    echo 'Работа скриптов завершена'
                }
            }
        }
    }
}